name: Build all

on:
  push:
    branches:
     - main
     - release/*
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - 'localization/**'
     - 'resources/**'
     - ".github/workflows/build_*.yml"
     - 'scripts/msix/**'
     - 'tests/**'

  pull_request:
    branches:
     - main
     - release/*
    paths:
     - 'deps/**'
     - 'deps_src/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - ".github/workflows/build_*.yml"
     - 'build_release_vs.bat'
     - 'build_release_vs2022.bat'
     - 'scripts/msix/**'
     - 'tests/**'

  schedule:
      - cron: '0 17 * * *' # run once a day at 1 AM Singapore time (UTC+8)

  workflow_dispatch: # allows for manual dispatch
    inputs:
      build-deps-only:
        description: 'Only build dependencies (bypasses caching)'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: Build Windows ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            os: windows-latest
    # Don't run scheduled builds on forks:
    if: ${{ !cancelled() && (github.event_name != 'schedule' || github.repository == 'OrcaSlicer/OrcaSlicer') }}
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: ${{ (matrix.arch == 'x64' && vars.SELF_HOSTED) && 'orca-win-server' || matrix.os }}
      arch: ${{ matrix.arch }}
      build-deps-only: ${{ inputs.build-deps-only || false }}
      force-build: ${{ github.event_name == 'schedule' }}
    secrets: inherit
